server:
  servlet:
    context-path: /privsense

spring:
  application:
    name: privsense
  main:
    allow-bean-definition-overriding: true

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /api/v1/**, /websocket/**
  show-actuator: false

privsense:
  # Common settings across all environments
  async:
    core-pool-size: 4
    max-pool-size: 8
    thread-name-prefix: privsense-async-

  # Default WebSocket configuration
  websocket:
    enabled: true
    heartbeat-in: 10000
    heartbeat-out: 10000
    allowed-origins: 
      - "http://localhost:*"
      - "http://127.0.0.1:*" 
      - "file://*"
    buffer-size-limit: 524288  # 512KB
    message-size-limit: 65536  # 64KB

  # Common detection thresholds
  detection:
    heuristic-threshold: 0.7
    regex-threshold: 0.8
    ner-threshold: 0.6
    reporting-threshold: 0.5
    regex:
      pattern-definitions:
        EMAIL_RFC5322:
          pattern: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
          score: 0.9
          pii-type: "EMAIL"
        US_SSN:
          pattern: "\\b(?!000|666|9\\d\\d)\\d{3}-(?!00)\\d{2}-(?!0000)\\d{4}\\b"
          score: 0.95
          pii-type: "SSN"
        US_PHONE:
          pattern: "\\b(?:\\+?1[-. ]?)?\\(?([0-9]{3})\\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})\\b"
          score: 0.8
          pii-type: "PHONE_NUMBER"
        CREDIT_CARD:
          pattern: "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\\d{3})\\d{11})\\b"
          score: 0.95
          pii-type: "CREDIT_CARD_NUMBER"
        DATE_FORMAT:
          pattern: "\\b(?:0[1-9]|1[0-2])/(?:0[1-9]|[12][0-9]|3[01])/(?:19|20)\\d{2}\\b|\\b(?:19|20)\\d{2}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])\\b"
          score: 0.6
          pii-type: "DATE" 
        IP_ADDRESS:
          pattern: "\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b"
          score: 0.7
          pii-type: "IP_ADDRESS"
        UK_NINO:
          pattern: "\\b[A-CEGHJ-PR-TW-Z]{1}[A-CEGHJ-NPR-TW-Z]{1}[0-9]{6}[A-D]{1}\\b"
          score: 0.95
          pii-type: "NATIONAL_ID"
        PASSPORT_NUMBER:
          pattern: "\\b[A-Z]{1,2}[0-9]{6,9}\\b"
          score: 0.9
          pii-type: "PASSPORT_NUMBER"
        IBAN:
          pattern: "\\b[A-Z]{2}[0-9]{2}[A-Z0-9]{4}[0-9]{7}([A-Z0-9]?){0,16}\\b"
          score: 0.9
          pii-type: "BANK_ACCOUNT"
        MAC_ADDRESS:
          pattern: "\\b([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})\\b"
          score: 0.7
          pii-type: "DEVICE_ID"
        IPV6_ADDRESS:
          pattern: "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4})"
          score: 0.7
          pii-type: "IP_ADDRESS"
        LATITUDE_LONGITUDE:
          pattern: "\\b[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?),\\s*[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)\\b"
          score: 0.8
          pii-type: "LOCATION"

  # API versioning and documentation
  api:
    version: v1.0
    content-type: application/json;charset=UTF-8